language: java

install: true


services:
  - docker

sudo: false

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: WITH_COVERALLS=true


cache:
  directories:
  - $HOME/.m2

install:
  - docker pull mongo
  - docker pull jboss/wildfly
  - docker build --tag=jboss/wildfly-admin \TicTacToeWeb

script:
 - if [ "$WITH_COVERALLS" == "true" ];
   then mvn -f pom.xml clean verify -Pjacoco org.eluder.coveralls:coveralls-maven-plugin:report;
   else mvn -f pom.xml clean verify;
   fi
